- id: badkamer_01
  alias: Badkamer dag modus
  trigger:
  - entity_id: light.badkamer_plafond_level
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - before: 0:00:00
      condition: time
    - after: sunrise
      condition: sun
  action:
  - service: light.turn_on
    data:
      brightness: 255
      entity_id: light.badkamer_plafond_level
- id: badkamer_02
  alias: Badkamer ochtend modus
  trigger:
  - entity_id: light.badkamer_plafond_level
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: time
        after: '7:00:00'
      - condition: sun
        before: sunrise
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'off'
    - condition: and
      conditions:
      - condition: time
        after: '5:00:00'
      - condition: sun
        before: sunrise
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
  - data:
      brightness: 50
      entity_id: light.badkamer_plafond_level
    service: light.turn_on
  - delay: 0:00:20
  - data:
      brightness: 255
      entity_id: light.badkamer_plafond_level
      transition: 30
    service: light.turn_on
- id: badkamer_03
  alias: Badkamer nacht modus
  trigger:
  - entity_id: light.badkamer_plafond_level
    from: 'off'
    platform: state
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: and
      conditions:
      - condition: time
        after: '0:00:00'
        before: '7:00:00'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'off'
    - condition: and
      conditions:
      - condition: time
        after: '0:00:00'
        before: '5:00:00'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
  - service: light.turn_on
    data:
      brightness: 50
      entity_id: light.badkamer_plafond_level
- id: mbr_01
  alias: Slaapkamer dim avond en ochtend
  trigger:
  - entity_id: light.mbr_plafond_level
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: time
      after: '22:00:00'
    #- after: sunset
    #  condition: sun
    - before: sunrise
      condition: sun
  action:
  - data:
      brightness: 26
      entity_id: light.mbr_plafond_level
    service: light.turn_on
- id: mbr_02
  alias: Slaapkamer overdag
  trigger:
  - entity_id: light.mbr_plafond_level
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - after: sunrise
      condition: sun
    - before: '22:00:00'
      condition: time
    #- before: sunset
    #  condition: sun
  action:
  - data:
      brightness: 254
      entity_id: light.mbr_plafond_level
    service: light.turn_on
- id: hum_low
  initial_state: false
  alias: low humidity
  trigger:
    platform: numeric_state
    entity_id: sensor.humdelta
    below: 1.9999
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.humidity
      option: low
- id: hum_med
  alias: medium humidity
  initial_state: false
  trigger:
    platform: numeric_state
    entity_id: sensor.humdelta
    above: 2
    below: 4
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.humidity
      option: medium
- id: hum_high
  alias: high humidity
  initial_state: false
  trigger:
    platform: numeric_state
    entity_id: sensor.humdelta
    above: 3.9999
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.humidity
      option: high
- id: fan_01a
  alias: Fan Speed high a
  trigger:
  # - entity_id: input_select.humidity
  #   from: low
  #   platform: state
  #   to: high
  - entity_id: input_select.fanstate
    platform: state
    to: high
  # - entity_id: input_select.humidity
  #   from: medium
  #   platform: state
  #   to: high
  action:
  - data:
      payload: high
      topic: /hass/itho
    service: mqtt.publish
  - data:
      entity_id: input_select.fanstate
      option: high
    service: input_select.select_option
  # - service: input_number.set_value
  #   data_template:
  #     entity_id: input_number.zolder_ventilatie
  #     value: 1
- id: fan_01b
  alias: Fan Speed high b
  initial_state: false
  trigger:
  - entity_id: sensor.wk_boilerstatus
    for:
      minutes: 1
    platform: state
    to: HW
  condition:
    - condition: state
      entity_id: light.badkamer_plafond_level
      state: 'on'
  action:
  - data:
      payload: high
      topic: /hass/itho
    service: mqtt.publish
  - data:
      entity_id: input_select.fanstate
      option: high
    service: input_select.select_option
  - service: input_number.set_value
    data_template:
      entity_id: input_number.zolder_ventilatie
      value: 1
- id: fan_02
  alias: Fan Speed high 2 medium
  initial_state: false
  trigger:
  - platform: state
    entity_id: input_select.humidity
    from: high
    to: medium
    for:
      minutes: 15
  condition:
    condition: state
    entity_id: sensor.itho_ventilatie
    state: high
  action:
  - service: mqtt.publish
    data:
      topic: /hass/itho
      payload: medium
  - service: input_select.select_option
    data:
      entity_id: input_select.fanstate
      option: medium
- id: fan_05
  alias: Fan Speed low
  trigger:
  # - platform: state
  #   entity_id: input_select.humidity
  #   to: low
  #   for:
  #     minutes: 15
  # - platform: state
  #   entity_id: sensor.wk_boilerstatus
  #   to: 'No'
  #   for:
  #     minutes: 15
  - platform: state
    entity_id: input_select.fanstate
    to: low
  # condition:
  #   condition: state
  #   entity_id: input_boolean.itho_not_low
  #   state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: /hass/itho
      payload: low
  - service: input_select.select_option
    data:
      entity_id: input_select.fanstate
      option: low
  - service: input_number.set_value
    data_template:
      entity_id: input_number.zolder_ventilatie
      value: 100
- id: fan_06
  alias: Fan Speed low 2 medium
  initial_state: false
  trigger:
  - platform: state
    entity_id: input_select.humidity
    from: low
    to: medium
  condition:
    condition: state
    entity_id: sensor.wk_boilerstatus
    state: 'No'
    for:
      minutes: 15
  action:
  - service: mqtt.publish
    data:
      topic: /hass/itho
      payload: medium
  - service: input_select.select_option
    data:
      entity_id: input_select.fanstate
      option: medium
- id: fan_07
  alias: Fan speed medium
  trigger:
  - platform: state
    entity_id: input_select.fanstate
    to: medium
  action:
  - service: mqtt.publish
    data:
      topic: /hass/itho
      payload: medium
  - service: input_select.select_option
    data:
      entity_id: input_select.fanstate
      option: medium
- id: itho_1
  alias: Restart ITHO on false status
  trigger:
  - entity_id: sensor.itho_ventilatie_status
    for:
      seconds: 20
    platform: state
    to: 'false'
  action:
  - data:
      payload: restart
      topic: /hass/itho
    service: mqtt.publish
  - delay: 00:01:00
  - data:
      payload: low
      topic: /hass/itho
    service: mqtt.publish
- id: itho_2
  alias: Itho not low
  trigger:
  - platform: state
    entity_id: sensor.itho_ventilatie
    to: high
  - platform: state
    entity_id: sensor.itho_ventilatie
    to: medium
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.itho_not_low
- id: itho_3
  alias: Itho low
  trigger:
  - platform: state
    entity_id: sensor.itho_ventilatie
    to: low
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.itho_not_low
- id: updater
  alias: Update Available Notifications
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: Version {{ states('sensor.current_version') }} for Home Assistant is
        available.
- id: Schemerlamp
  alias: Turn on Schemerlamp when sun sets
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: group.all_devices
    state: home
  action:
    service: switch.turn_on
    entity_id: switch.__switch_8_0
- id: wasmachine_01
  alias: Washer Start
  trigger:
    platform: state
    entity_id: sensor.washer_pwrup
    from: 'False'
    to: 'True'
    for:
      minutes: 3
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.washer_switch
- id: wasmachine_02
  alias: Wasmachine Klaar
  trigger:
    platform: state
    entity_id: sensor.washer_pwrup
    from: 'True'
    to: 'False'
    for:
      minutes: 3
  condition:
    condition: state
    entity_id: input_boolean.washer_switch
    state: 'on'
  action:
  - service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: Wasmachine is klaar!
  - service: input_boolean.turn_off
    entity_id: input_boolean.washer_switch
- id: droger_01
  alias: Dryer Start
  trigger:
    platform: state
    entity_id: sensor.dryer_pwrup
    from: 'False'
    to: 'True'
    for:
      minutes: 3
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.dryer_switch
- id: droger_02
  alias: Droger Klaar
  trigger:
    platform: state
    entity_id: sensor.dryer_pwrup
    from: 'True'
    to: 'False'
    for:
      minutes: 3
  condition:
    condition: state
    entity_id: input_boolean.dryer_switch
    state: 'on'
  action:
  - service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: Droger is klaar!
  - service: input_boolean.turn_off
    entity_id: input_boolean.dryer_switch
- id: Hank_wk1
  alias: Hank wk1
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_knop_wk
      scene_id: 1
  action:
    #service: rest_command.play_pause
    service: scene.turn_on
    entity_id: scene.woonkamer_low
- id: Hank_wk2
  alias: Hank wk2
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_knop_wk
      scene_id: 2
  action:
    service: scene.turn_on
    entity_id: scene.woonkamer_medium
- id: Hank_wk3
  alias: Hank wk3
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_knop_wk
      scene_id: 3
  action:
    service: scene.turn_on
    entity_id: scene.woonkamer_off
- id: Hank_wk4
  alias: Hank wk4
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_knop_wk
      scene_id: 4
  action:
    service: scene.turn_on
    entity_id: scene.woonkamer_full
- id: Thermostaat_1
  alias: Thermostaat 1
  trigger:
  - entity_id: sensor.thermostaat_tempsetpoint
    platform: numeric_state
    below: 15.1
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: time
        after: '20:00:00'
      - condition: time
        before: '2:00:00'
    - condition: state
      entity_id: group.woonkamer
      state: 'on'
    - condition: state
      entity_id: sensor.thermostaat_activeprogram
      state: '0'
  action:
    - service: ifttt.trigger
      data_template:
        event: "SetTemp"
        value1: >
          {{ states.sensor.maxtempsetpoint.state }}
    - delay: '00:00:01'
    - service: input_number.set_value
      data_template:
        entity_id: input_number.iftt_temp_triggered_SP
        value: >
          {{ states.sensor.maxtempsetpoint.state }}
    - service: input_boolean.turn_on
      entity_id: input_boolean.iftt_temp_triggered
- id: Thermostaat_2
  alias: Thermostaat 2
  trigger:
  - platform: state
    entity_id: group.woonkamer
    to: 'off'
    for:
      minutes: 5
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: sensor.thermostaat_activeprogram
      state: '0'
    - condition: or
      conditions:
      - condition: time
        after: '20:00:00'
      - condition: time
        before: '2:00:00'
  action:
    - service: ifttt.trigger
      data:
        event: "SetTemp"
        value1: 15
    - service: input_number.set_value
      data_template:
        entity_id: input_number.iftt_temp_triggered_sp
        value: 15
    - delay: '00:00:01'
    - service: input_boolean.turn_on
      entity_id: input_boolean.iftt_temp_triggered
- id: wk_muur1
  alias: WK Muur uit
  trigger:
    - entity_id: group.woonkamer_ex_muur
      from: 'on'
      platform: state
      to: 'off'
      for:
        seconds: 10
  action:
    # kerstboom
    - service: switch.turn_off
      entity_id: switch.fibaro_switch_switch
    - service: light.turn_off
      data:
        transition: 20
        entity_id: light.wk_muur_level
- id: wk_muur2
  alias: WK Muur aan op Beweging
  trigger:
    - entity_id: sensor.wk_multisensor_burglar
      platform: state
      to: '8'
    - entity_id: sensor.wk_multisensor_burglar
      platform: state
      to: '3'
  condition:
    condition: template
    value_template: "{{ states.sun.sun.attributes.elevation  | int < 10 }}"
    # condition: and
    # conditions:
    #   - condition: or
    #     conditions:
    #       - condition: template
    #         value_template: "{{ states.sun.sun.attributes.elevation  | int < 10 }}"
    #       # - condition: sun
    #       #   after: sunset
    #       # - condition: sun
    #       #   before: sunrise
  action:
    - service: light.turn_on
      data:
        entity_id: light.wk_muur_level
        brightness: 50
    # kerstboom
    - service: switch.turn_on
      entity_id: switch.fibaro_switch_switch
- id: wk_multisensor_battery1
  alias: wk_multisensor_battery1
  trigger:
    - entity_id: sensor.wk_multisensor_battery_level
      platform: numeric_state
      below: 25
  action:
    service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: wk_multisensor batterij niveau is {{ states.zwave.wk_multisensor.attributes.battery_level }}%
- id: wk_multisensor_battery2
  alias: wk_multisensor_battery2
  trigger:
    platform: time
    # When 'after' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    at: '20:00:00'
  condition:
    - entity_id: sensor.wk_multisensor_battery_level
      condition: numeric_state
      below: 25
  action:
    service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: wk_multisensor batterij niveau is {{ states.zwave.wk_multisensor.attributes.battery_level }}%
- id: zolder_multisensor_battery1
  alias: zolder_multisensor_battery1
  trigger:
    - entity_id: sensor.zolder_multisensor_battery_level
      platform: numeric_state
      below: 25
  action:
    service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: zolder_multisensor batterij niveau is {{ states.zwave.wk_multisensor.attributes.battery_level }}%
- id: zolder_multisensor_battery2
  alias: zolder_multisensor_battery2
  trigger:
    platform: time
    # When 'after' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    at: '20:00:00'
  condition:
    - entity_id: sensor.zolder_multisensor_battery_level
      condition: numeric_state
      below: 25
  action:
    service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: zolder_multisensor batterij niveau is {{ states.zwave.wk_multisensor.attributes.battery_level }}%
- id: thermo_dide1
  alias: thermo_dide1
  trigger:
    - platform: time
      at: '17:00:00'
  action:
    service: mqtt.publish
    data_template:
      topic: "/fhem/ThermDide/desiredTemperature/set"
      retain: true
      payload: '17'
- id: thermo_dide2
  alias: thermo_dide2
  trigger:
    - platform: state
      entity_id: input_boolean.zolder_multisensor_burglar
      to: 'on'
  condition:
    - condition: time
      after: '9:00:00'
      before: '17:00:00'
  action:
    service: mqtt.publish
    data_template:
      topic: "/fhem/ThermDide/desiredTemperature/set"
      retain: true
      payload: '17'
- id: thermo_dide3
  alias: thermo_dide3
  trigger:
    - platform: state
      entity_id: input_boolean.zolder_multisensor_burglar
      to: 'off'
  condition:
    - condition: time
      after: '9:00:00'
      before: '17:00:00'
  action:
    service: mqtt.publish
    data_template:
      topic: "/fhem/ThermDide/desiredTemperature/set"
      retain: true
      payload: '17'
- id: thermo_dide_uit
  alias: thermo_dide_uit
  trigger:
    platform: time
    at: '19:00:00'
  action:
    service: mqtt.publish
    data_template:
      topic: "/fhem/ThermDide/desiredTemperature/set"
      retain: true
      payload: '13'
- id: thermo_dide_10
  alias: Set temp slider Dide temperature
  trigger:
    platform: mqtt
    topic: "/fhem/ThermDide/desiredTemperature"
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.slaapkamer_dide_setpoint
      value: '{{ trigger.payload}}'
- id: thermo_dide_11
  alias: Temp slider moved
  trigger:
    platform: state
    entity_id: input_number.slaapkamer_dide_setpoint
  action:
    service: mqtt.publish
    data_template:
      topic: "/fhem/ThermDide/desiredTemperature/set"
      retain: true
      payload: '{{ states.input_number.slaapkamer_dide_setpoint.state | int }}'
- id: beweging_zolder1
  alias: Beweging zolder aan
  trigger:
    - platform: state
      entity_id: sensor.zolder_multisensor_burglar
      to: '8'
    - platform: state
      entity_id: sensor.zolder_multisensor_burglar
      to: '3'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.zolder_multisensor_burglar
- id: beweging_zolder2
  alias: Beweging zolder uit
  trigger:
    - platform: state
      entity_id: sensor.zolder_multisensor_burglar
      to: '0'
      for:
        minutes: 25
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.zolder_multisensor_burglar
- id: occupancy_sim_on
  alias: Simulate Occupancy - on
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: input_boolean.occupancy_simulation
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.woonkamer_low
- id: hass_startup
  alias: 'HA_Start'
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    - service: group.set_visibility
      entity_id: group.zolder_ventilatie_moving
      data:
        visible: False
    - service: input_number.set_value
      data_template:
        entity_id: input_number.zolder_ventilatie
        value: "100"
- id: zolder_ventilatie_01
  alias: "Zolder Ventilatie Uit"
  trigger:
    - entity_id: sensor.wk_boilerstatus
      platform: state
      to: HW
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.zolder_ventilatie
        value: "0"
- id: zolder_ventilatie_02
  alias: Zolder Ventilatie aan
  trigger:
  - platform: state
    entity_id: sensor.wk_boilerstatus
    to: 'No'
  - platform: state
    entity_id: sensor.wk_boilerstatus
    to: 'CH'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.fanstate
        state: 'low'
      - condition: state
        entity_id: input_select.fanstate
        state: 'medium'
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.zolder_ventilatie
      value: 100
