- id: itho_1
  alias: Restart ITHO on false status
  trigger:
  - entity_id: sensor.itho_ventilatie_status
    for:
      seconds: 20
    platform: state
    to: 'false'
  action:
  - data:
      payload: restart
      topic: /hass/itho/cmd
    service: mqtt.publish
  - delay: 00:01:00
  - data:
      payload: State,1
      topic: /hass/itho/cmd
    service: mqtt.publish
- id: updater
  alias: Update Available Notifications
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: Version {{ states('sensor.current_version') }} for Home Assistant is
        available.
- id: wasmachine_01
  alias: Washer Start
  trigger:
    platform: state
    entity_id: sensor.washer_pwrup
    from: 'False'
    to: 'True'
    for:
      minutes: 3
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.washer_switch
- id: wasmachine_02
  alias: Wasmachine Klaar
  trigger:
    platform: state
    entity_id: sensor.washer_pwrup
    from: 'True'
    to: 'False'
    for:
      minutes: 3
  condition:
    condition: state
    entity_id: input_boolean.washer_switch
    state: 'on'
  action:
  - service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: Wasmachine is klaar!
  - service: input_boolean.turn_off
    entity_id: input_boolean.washer_switch
- id: droger_01
  alias: Dryer Start
  trigger:
    platform: state
    entity_id: sensor.dryer_pwrup
    from: 'False'
    to: 'True'
    for:
      minutes: 3
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.dryer_switch
- id: droger_02
  alias: Droger Klaar
  trigger:
    platform: state
    entity_id: sensor.dryer_pwrup
    from: 'True'
    to: 'False'
    for:
      minutes: 3
  condition:
    condition: state
    entity_id: input_boolean.dryer_switch
    state: 'on'
  action:
  - service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: Droger is klaar!
  - service: input_boolean.turn_off
    entity_id: input_boolean.dryer_switch
- id: Hank_wk1
  alias: Hank wk1
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_knop_wk
      scene_id: 1
  action:
    service: script.turn_on
    entity_id: script.woonkamer_low
- id: Hank_wk2
  alias: Hank wk2
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_knop_wk
      scene_id: 2
  action:
    service: script.turn_on
    entity_id: script.woonkamer_medium
- id: Hank_wk3
  alias: Hank wk3
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_knop_wk
      scene_id: 3
  action:
  - service: script.turn_on
    entity_id: script.woonkamer_off
  - service: input_boolean.turn_on
    entity_id: input_boolean.huis_slaapstand
- id: Hank_wk4
  alias: Hank wk4
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_knop_wk
      scene_id: 4
  action:
    service: script.turn_on
    entity_id: script.woonkamer_full
- id: Thermostaat_3
  alias: Thermostaat 3
  trigger:
  - platform: time
    at: '2:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.huis_slaapstand
    state: 'off'
  action:
  - service: ifttt.trigger
    data:
      event: SetTemp
      value1: 15
  - service: input_number.set_value
    data_template:
      entity_id: input_number.iftt_temp_triggered_sp
      value: 15
  - delay: 00:00:01
  - service: input_boolean.turn_on
    entity_id: input_boolean.iftt_temp_triggered
  - service: input_boolean.turn_on
    entity_id: input_boolean.huis_slaapstand
- id: wk_muur1
  alias: WK Muur uit
  trigger:
  - entity_id: group.woonkamer_ex_muur
    from: 'on'
    platform: state
    to: 'off'
    for:
      seconds: 10
  action:
  - service: light.turn_off
    data:
      transition: 20
      entity_id: light.wk_muur_level
- id: wk_muur2
  alias: WK Muur aan op Beweging
  trigger:
  - entity_id: sensor.wk_multisensor_burglar
    platform: state
    to: '8'
  - entity_id: sensor.wk_multisensor_burglar
    platform: state
    to: '3'
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ states.sun.sun.attributes.elevation  | int < 8 }}'
    - condition: state
      entity_id: input_boolean.huis_slaapstand
      state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.wk_muur_level
      brightness: 50
- id: wk_muur3
  alias: WK Muur na zonsopgang uit
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 8
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.woonkamer_ex_muur
      state: 'off'
    - condition: time
      before: '12:00:00'
  action:
  - service: light.turn_off
    data:
      entity_id: light.wk_muur_level
- id: wk_muur4
  alias: WK Muur uit bij geen Beweging
  trigger:
  - entity_id: sensor.wk_multisensor_burglar
    platform: state
    to: '0'
    for:
      minutes: 10
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ states.sun.sun.attributes.elevation  | int > 8 }}'
    - condition: state
      entity_id: input_boolean.huis_slaapstand
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: light.wk_muur_level
- id: wk_multisensor_battery1
  alias: wk_multisensor_battery1
  trigger:
  - entity_id: sensor.wk_multisensor_battery_level
    platform: numeric_state
    below: 25
  action:
    service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: wk_multisensor batterij niveau is {{ states.zwave.wk_multisensor.attributes.battery_level
        }}%
- id: wk_multisensor_battery2
  alias: wk_multisensor_battery2
  trigger:
    platform: time
    at: '20:00:00'
  condition:
  - entity_id: sensor.wk_multisensor_battery_level
    condition: numeric_state
    below: 25
  action:
    service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: wk_multisensor batterij niveau is {{ states.zwave.wk_multisensor.attributes.battery_level
        }}%
- id: zolder_multisensor_battery1
  alias: zolder_multisensor_battery1
  trigger:
  - entity_id: sensor.zolder_multisensor_battery_level
    platform: numeric_state
    below: 25
  action:
    service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: zolder_multisensor batterij niveau is {{ states.zwave.wk_multisensor.attributes.battery_level
        }}%
- id: zolder_multisensor_battery2
  alias: zolder_multisensor_battery2
  trigger:
    platform: time
    at: '20:00:00'
  condition:
  - entity_id: sensor.zolder_multisensor_battery_level
    condition: numeric_state
    below: 25
  action:
    service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: zolder_multisensor batterij niveau is {{ states.zwave.wk_multisensor.attributes.battery_level
        }}%
- id: thermo_zolder1
  alias: thermo_zolder1
  trigger:
  - platform: time
    at: '17:00:00'
  action:
  - service: mqtt.publish
    data_template:
      topic: /zolder/kamerdide/thermostaat/desiredTemperature/set
      retain: true
      payload: '17'
  - service: mqtt.publish
    data_template:
      topic: /zolder/kamerfien/thermostaat/desiredTemperature/set
      retain: true
      payload: '18'
- id: thermo_zolder2a
  alias: Thermostaat Zolder ochtend laat
  trigger:
  - entity_id: input_boolean.zolder_multisensor_burglar
    platform: state
    to: 'on'
  condition:
  - after: '9:00:00'
    before: '17:00:00'
    condition: time
  action:
  - data_template:
      payload: '17'
      retain: true
      topic: /zolder/kamerdide/thermostaat/desiredTemperature/set
    service: mqtt.publish
  - data_template:
      payload: '18'
      retain: true
      topic: /zolder/kamerfien/thermostaat/desiredTemperature/set
    service: mqtt.publish
- id: thermo_zolder2b
  alias: Thermostaat Zolder ochtend vroeg
  trigger:
  - at: '6:30:00'
    platform: time
  condition: []
  action:
  - data_template:
      payload: '16'
      retain: true
      topic: /zolder/kamerdide/thermostaat/desiredTemperature/set
    service: mqtt.publish
  - data_template:
      payload: '17'
      retain: true
      topic: /zolder/kamerfien/thermostaat/desiredTemperature/set
    service: mqtt.publish
- id: thermo_zolder3
  alias: Thermostaat Zolder ochtend uit
  trigger:
  - entity_id: input_boolean.zolder_multisensor_burglar
    platform: state
    to: 'off'
  condition:
  - after: '6:30:00'
    before: '17:00:00'
    condition: time
  action:
  - data_template:
      payload: '13'
      retain: true
      topic: /zolder/kamerdide/thermostaat/desiredTemperature/set
    service: mqtt.publish
  - data_template:
      payload: '13'
      retain: true
      topic: /zolder/kamerfien/thermostaat/desiredTemperature/set
    service: mqtt.publish
- id: thermo_zolder_uit
  alias: Thermostaat Zolder uit
  trigger:
    platform: time
    at: '19:00:00'
  action:
  - service: mqtt.publish
    data_template:
      topic: /zolder/kamerdide/thermostaat/desiredTemperature/set
      retain: true
      payload: '13'
  - service: mqtt.publish
    data_template:
      topic: /zolder/kamerfien/thermostaat/desiredTemperature/set
      retain: true
      payload: '13'
- id: thermo_dide_10
  alias: Set temp slider Dide temperature
  trigger:
    platform: mqtt
    topic: /zolder/kamerdide/thermostaat/desiredTemperature
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.slaapkamer_dide_setpoint
      value: '{{ trigger.payload}}'
- id: thermo_dide_11
  alias: Temp slider moved Dide
  trigger:
    platform: state
    entity_id: input_number.slaapkamer_dide_setpoint
  action:
    service: mqtt.publish
    data_template:
      topic: /zolder/kamerdide/thermostaat/desiredTemperature/set
      retain: true
      payload: '{{ states.input_number.slaapkamer_dide_setpoint.state }}'
- id: thermo_fien_10
  alias: Set temp slider Fien temperature
  trigger:
    platform: mqtt
    topic: /zolder/kamerfien/thermostaat/desiredTemperature
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.slaapkamer_fien_setpoint
      value: '{{ trigger.payload}}'
- id: thermo_fien_11
  alias: Temp slider moved Fien
  trigger:
    platform: state
    entity_id: input_number.slaapkamer_fien_setpoint
  action:
    service: mqtt.publish
    data_template:
      topic: /zolder/kamerfien/thermostaat/desiredTemperature/set
      retain: true
      payload: '{{ states.input_number.slaapkamer_fien_setpoint.state }}'
- id: beweging_zolder1
  alias: Beweging zolder aan
  trigger:
  - platform: state
    entity_id: sensor.zolder_multisensor_burglar
    to: '8'
  - platform: state
    entity_id: sensor.zolder_multisensor_burglar
    to: '3'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.zolder_multisensor_burglar
- id: beweging_zolder2
  alias: Beweging zolder uit
  trigger:
  - platform: state
    entity_id: sensor.zolder_multisensor_burglar
    to: '0'
    for:
      minutes: 25
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.zolder_multisensor_burglar
- id: occupancy_sim_on
  alias: Simulate Occupancy - on
  trigger:
  - platform: state
    entity_id: input_boolean.occupancy_simulation
    to: 'on'
  action:
    service: script.turn_on
    entity_id: script.woonkamer_low
- id: occupancy_sim_off
  alias: occupancy_sim_off
  trigger:
  - platform: state
    entity_id: sensor.wk_multisensor_burglar
    to: '8'
  - platform: state
    entity_id: sensor.wk_multisensor_burglar
    to: '3'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.occupancy_simulation
- id: occupancy_sim_goodnight
  alias: occupancy_sim_goodnight
  trigger:
    platform: time
    at: '22:30'
  condition:
  - condition: state
    entity_id: input_boolean.occupancy_simulation
    state: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.occupancy_simulation
  - service: light.turn_off
    entity_id: group.woonkamer
  - service: switch.turn_off
    entity_id: group.woonkamer
  - service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: Lampen in huis gaan uit
- id: hass_startup
  alias: HA_Start
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
  - service: group.set_visibility
    entity_id: group.zolder_ventilatie_moving
    data:
      visible: false
  - service: input_number.set_value
    data_template:
      entity_id: input_number.zolder_ventilatie
      value: '100'
- id: zolder_ventilatie_01
  alias: Zolder Ventilatie Uit
  trigger:
  - entity_id: sensor.wk_boilerstatus
    platform: state
    to: HW
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.zolder_ventilatie
      value: '0'
- id: zolder_ventilatie_02
  alias: Zolder Ventilatie aan
  trigger:
  - platform: state
    entity_id: sensor.wk_boilerstatus
    to: 'No'
  - platform: state
    entity_id: sensor.wk_boilerstatus
    to: CH
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.fanstate
      state: low
    - condition: state
      entity_id: input_select.fanstate
      state: medium
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.zolder_ventilatie
      value: 100
- id: reset_huis_slaapstand
  alias: Reset huis_slaapstand
  trigger:
    platform: time
    at: 04:00:00
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.huis_slaapstand
- id: set_huis_slaapstand
  alias: Set huis_slaapstand
  trigger:
    platform: state
    entity_id: group.woonkamer
    to: 'off'
  condition:
    condition: or
    conditions:
    - condition: time
      after: '21:00:00'
    - condition: time
      before: '4:00:00'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.huis_slaapstand
- id: notify_when_not_home_1
  alias: Notify and activate Occupancy Simulation 1
  trigger:
  - platform: time
    at: '18:10:00'
  condition:
  - condition: and
    conditions:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: group.woonkamer
      state: 'off'
  action:
  # - service: notify.pushbullet
  #   data:
  #     target: device/Nexus5X
  #     message: Lampen in huis gaan aan - aanwezigheidssimulatie
  - service: input_boolean.turn_on
    entity_id: input_boolean.occupancy_simulation
- id: notify_when_not_home_2
  alias: Notify and activate Occupancy Simulation 2
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '18:10:00'
    - condition: state
      entity_id: group.woonkamer
      state: 'off'
    - condition: time
      before: '22:30:00'
  action:
  - service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: Lampen in huis gaan aan - aanwezigheidssimulatie
  - service: input_boolean.turn_on
    entity_id: input_boolean.occupancy_simulation
- id: appdaemon_alive_1
  alias: appdaemon_alive_1
  trigger:
  - platform: state
    entity_id: input_boolean.appdaemon_alive
    to: 'off'
    for:
      minutes: 5
  action:
  - service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: Appdaemon draait niet
- id: appdaemon_alive_2
  alias: appdaemon_alive_2
  trigger:
    platform: time
    minutes: /5
    seconds: 0
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.appdaemon_alive
- id: pingpong
  alias: Telegram bot that reply pong to ping
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /ping
  action:
  - service: notify.telegram
    data:
      message: 'pong

        pang'
- id: vals_woonkamer_on
  alias: Detect vals aantal lampen aan in woonkamer
  trigger:
  - entity_id: sensor.wk_multisensor_burglar
    platform: state
    to: '0'
    for:
      minutes: 60
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '22:00:00'
    - condition: template
      value_template: '{{ states.sensor.woonkamer_number_of_lights_on.state | int
        <= 2  }}'
  action:
  - service: script.turn_on
    entity_id: script.woonkamer_off
  - service: input_boolean.turn_on
    entity_id: input_boolean.huis_slaapstand
# - id: zolder_warm_in_1
#   alias: Temperatuur op zolder hoger dan buiten
#   trigger:
#   - entity_id: sensor.zolder_delta_t
#     platform: numeric_state
#     below: 0
#   condition:
#   - condition: numeric_state
#     entity_id: sensor.zolder_max_t
#     above: 23
#   action:
#   - service: input_boolean.turn_on
#     entity_id: input_boolean.zolder_te_warm
# - id: zolder_warm_in_2
#   alias: Temperatuur op zolder veel hoger dan buiten
#   trigger:
#   - entity_id: sensor.zolder_delta_t
#     platform: numeric_state
#     below: 0
#   condition:
#   - condition: numeric_state
#     entity_id: sensor.zolder_max_t
#     above: 27
#   action:
#   - service: input_boolean.turn_on
#     entity_id: input_boolean.zolder_veel_te_warm
# - id: zolder_warm_uit
#   alias: Temperatuur op zolder lager dan buiten
#   trigger:
#   - entity_id: sensor.zolder_delta_t
#     platform: numeric_state
#     above: 0
#     for:
#       minutes: 10
#   action:
#   - service: input_boolean.turn_off
#     entity_id: input_boolean.zolder_te_warm
#   - service: input_boolean.turn_off
#     entity_id: input_boolean.zolder_veel_te_warm
# - id: azimuth_backside_on
#   trigger:
#   - platform: numeric_state
#     entity_id: sensor.azimuth
#     above: 54
#   action:
#   - service: input_boolean.turn_on
#     entity_id: input_boolean.azimuth_backside
# - id: azimuth_backside_off
#   trigger:
#   - platform: numeric_state
#     entity_id: sensor.azimuth
#     above: 234
#   action:
#   - service: input_boolean.turn_off
#     entity_id: input_boolean.azimuth_backside
- id: azimuth_scherm_op
  alias: Zonnescherm op tegen avond
  trigger:
  - platform: state
    entity_id: input_boolean.azimuth_backside
    to: "off"
  - platform: sun
    event: sunset
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.level
- id: 'sander_gaat_weg'
  alias: Sander gaat weg
  trigger:
  - entity_id: device_tracker.phone_sander
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      message: Sander verlaat het huis
      target: device/Nexus5X
    service: notify.pushbullet
- id: heal_network
  alias: heal at 2:32am
  trigger:
    platform: time
    at: '2:32:00'
  action:
    service: zwave.heal_network
- id: ping_raumfeld
  alias: Ping Raumfeld
  trigger:
    platform: state
    entity_id: binary_sensor.ping_raumfeld
    to: "off"
    for:
      minutes: 1
  action:
    service: notify.pushbullet
    data:
      target: device/Nexus5X
      message: Raumfeld offline
