homeassistant:
  # # Name of the location where Home Assistant is running
  # name: Home Linda en Sander
  # # Location required to calculate the time the sun rises and sets
  # latitude: !secret latitude
  # longitude: !secret longitude

  # # Impacts weather/sunrise data (altitude above sea level in meters)
  # elevation: 0


  # # metric for Metric, imperial for Imperial
  # unit_system: metric
  # # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # time_zone: !secret time_zone
  # # customize: !include customize.yaml
  # #packages: !include_dir_named packages
  # # auth_providers:
  # #  - type: homeassistant
  # ##  - type: legacy_api_password

lovelace:
#   mode: yaml

my:

person:

recorder:
  db_url: postgresql://homeassistant:ereadsta@192.168.0.9/homeassistant
  purge_keep_days: 7
  exclude:
    domains:
      # - automation
      - weblink
      - updater
      #- device_tracker
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date
      - scene.rainbow_1
      - scene.rainbow_2
      - scene.rainbow_3
      - scene.rainbow_4
      - scene.rainbow_5
      - scene.rainbow_6
      - scene.rainbow_7
      - scene.rainbow_8
      - zone.home
  include:
    entities:
      - device_tracker.phone_linda
      - device_tracker.phone_nexus5x
      - device_tracker.phone_phone
      - device_tracker.phone_sander
      - device_tracker.phone_sander_bt
      - device_tracker.phone_sander_wifi
      - device_tracker.nut_sander
      - device_tracker.nut_linda

logger:
  default: info
  # default: debug
  # logs:
    # homeassistant.components.esphome: debug
    # homeassistant.bootstrap: debug
    #critical
  # info
#  logs:
#    homeassistant.components.sensor: debug
#    homeassistant.components.script: debug
#    homeassistant.components.automation: debug
#    homeassistant.components.device_tracker: debug

#splunk:
#  token: !secret splunk_token

# Enables the frontend
frontend:
  # themes: !include_dir_merge_named themes

config:

system_health:

cloud:



http:
  # Uncomment this if you are using SSL or running in Docker etc
  #ssl_certificate: !secret ssl_ssl_certificate
  #ssl_key: !secret ssl_ssl_key
  # base_url: !secret ssl_base_url

api:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
    - google_cast
mobile_app:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

weather:
  - platform: buienradar

sensor: !include includes/sensors.yaml
binary_sensor: !include includes/binary_sensors.yaml
switch: !include includes/switches.yaml
fan: !include includes/fan.yaml
plant: !include includes/plant.yaml

counter:
  douches:
    initial: 0
    step: 1
    icon: mdi:shower



device_tracker: !include includes/device_tracker.yaml

group: !include includes/groups.yaml
# zone: !include includes/zones.yaml

automation: !include automations.yaml
# automation old: !include_dir_merge_list automation



#light: !include_dir_list light/
#script: !include_dir_list script/
#script: !include script/badkamer_script.yaml
script: !include scripts.yaml
#script: !include includes/script/scripts.yaml
#  - !include script/woonkamer.yaml
  #- !include script/mbr.yaml
#script: !include script/group_visibility.yaml
input_boolean: !include includes/input_booleans.yaml
scene: !include scenes.yaml
#scene_old: !include_dir_list scenes
cover: !include includes/cover.yaml


# MQTT config
mqtt:
  broker: 192.168.0.9
  port: 1883
  client_id: home-assistant
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant

# Z-Wave config
# zwave:
#   usb_path: /dev/ttyACM0
#   autoheal: false
#   device_config:
#     cover.level:
#       invert_openclose_buttons: true

# # IFTTT
# ifttt:
#   key: !secret ifttt_key

climate: !include includes/climate.yaml




notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id1
  # - name: html5
  #   platform: html5
  #   gcm_api_key: !secret chrome_gcm_api_key
  #   gcm_sender_id: !secret chrome_gcm_sender_id
 

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    allowed_chat_ids:
      - !secret telegram_chat_id1


# cast:
#   media_player:

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - 'co_status'
      - 'smoke_status'
      - 'battery_health'
  binary_sensors:
    monitored_conditions:
      - 'online'



input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
light: !include includes/light.yaml


input_text:
  # valvemoving:
  #   name: "Action:"
  #   initial: Valve is moving
  itho_reason:
    name: Itho Reason



shopping_list:


influxdb:
  host: 192.168.0.9
  max_retries: 3
  default_measurement: state
  include:
    entities:
      - cover.radiator_dide
    domains:
      - sensor
      - light
      - input_select
      - input_boolean
      - input_number
      - input_text
      - switch
      - binary_sensor
      - cover
  tags:
    source: hass
  tags_attributes:
    - friendly_name

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

timer:
  fanrunout:
    icon: mdi:fan
  convectorput_runout:



input_datetime:
  sousvidefinish:
    name: Sous Vide klaar
    has_time: true
    initial: "09:00"
  sousvidelengte:
    name: Sous Vide Lengte
    has_time: true
    initial: "00:45"


pi_hole:
  host: '192.168.0.6'
  ssl: false
  verify_ssl: false
  api_key: !secret pihole_api

rest_command:
  appdaemon_restart:
    url: "http://192.168.0.9:8126/container/appdaemon4/restart"
  nodered_restart:
    url: "http://192.168.0.9:8126/container/nodered/restart"
    # method: POST
    # content_type: "application/x-www-form-urlencoded"
  reload_zwavejs: 
    url: !secret reload_zwavejs_url
    method: POST
    headers:
      authorization: !secret reload_zwavejs_token
      content-type: application/json


ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg


