homeassistant:
  # Name of the location where Home Assistant is running
  name: Home Linda en Sander
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0


  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize: !include customize.yaml


recorder:
  db_url: postgres://@/homeassistant
  purge_interval: 2
  purge_keep_days: 7

logger:
  default: info
    #critical
  # info
#  logs:
#    homeassistant.components.sensor: debug
#    homeassistant.components.script: debug
#    homeassistant.components.automation: debug
#    homeassistant.components.device_tracker: debug

# Enables the frontend
frontend:

config:

http:
  # Uncomment this to add a password (recommended!)
  #api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  #ssl_certificate: !secret ssl_ssl_certificate
  #ssl_key: !secret ssl_ssl_key
  #base_url: !secret ssl_base_url


# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


sensor: !include sensors.yaml
switch: !include switches.yaml


# Text to speech
tts:
  platform: google

device_tracker: !include device_tracker.yaml

group: !include groups.yaml
zone: !include zones.yaml
automation: !include automations.yaml
#automation: !include_dir_list automation/

#light: !include_dir_list light/
#script: !include_dir_list script/
script: !include script/badkamer_script.yaml
#script: !include script/group_visibility.yaml
input_boolean: !include input_booleans.yaml
scene: !include_dir_list scenes

# emulated_hue:
#   host_ip: 192.168.0.9
#   listen_port: 8300
#   # advertise_ip: 192.168.0.99
#   # advertise_port: 80
#   expose_by_default: true
#   exposed_domains:
#     - light



# android_ip_webcam:
#   - host: 192.168.0.56

# MQTT config
mqtt:
  broker: 192.168.0.9
  port: 1883
  client_id: home-assistant
  keepalive: 60
#  username: USERNAME
#  password: PASSWORD
  protocol: 3.1
  #discovery: "discovery/#"
#  birth_message:
#    topic: 'hass/status'
#    payload: 'online'
#    qos: 1
#    retain: true
#  will_message:
#    topic: 'hass/status'
#    payload: 'offline'
#    qos: 1
#    retain: true

# Z-Wave config
zwave:
  usb_path: /dev/ttyACM0
  new_entity_ids: true



#sensor:
#  - platform: dsmr
#    port: /dev/ttyP12
#    dsmr_version: 2.2

#group:
#  meter_readings:
#    name: Meter readings
#    entities:
#      - sensor.power_consumption_low
#      - sensor.power_consumption_normal
#      - sensor.gas_consumption

#climate:
#  platform: nefit
#  name: Heating
#  serial: !secret nefit_serial
#  accesskey: !secret nefit_accesskey
#  password: ! secret nefit_password

python_script:

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
#  - name: chrome
#    platform: html5
#    gcm_api_key: !secret chrome_gcm_api_key
#    gcm_sender_id: !secret chrome_gcm_sender_id

media_player:
  - platform: cast

nest:
  client_id: 22d9982a-426c-4d22-9046-ebbb52bd77e6
  client_secret: wv45yIASm9g8KQ5DTD4sWlxuG
  sensors:
    monitored_conditions:
      - 'co_status'
      - 'smoke_status'
      - 'battery_health'
  binary_sensors:
    monitored_conditions:
      - 'online'

input_select: !include input_select.yaml

light:
  - platform: mqtt_json
    command_topic: "/eerste/slaapkamer/rgb/set"
    brightness: true
    name: mqtt_json_slaapkamer
    state_topic: "/eerste/slaapkamer/rgb/state"
    rgb: true
    effect: true
    effect_list: [colorfade_slow, colorfade_fast, flash, firegrad, rainbowcycle]
    flash: true
    optimistic: false
    qos: 0
  - platform: mqtt_json
    command_topic: "/eerste/slaapkamer/rgb/set1"
    brightness: true
    name: mqtt_json_slaapkamer1
    state_topic: "/eerste/slaapkamer/rgb/state"
    rgb: true
    effect: true
    effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
    flash: true
    optimistic: false
    qos: 0
  - platform: mqtt_json
    command_topic: "/eerste/slaapkamer/rgb/set2"
    brightness: true
    name: mqtt_json_slaapkamer2
    state_topic: "/eerste/slaapkamer/rgb/state"
    rgb: true
    effect: true
    effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
    flash: true
    optimistic: false
    qos: 0
  - platform: mqtt_json
    command_topic: "/eerste/slaapkamer/rgb/set3"
    brightness: true
    name: mqtt_json_slaapkamer3
    state_topic: "/eerste/slaapkamer/rgb/state"
    rgb: true
    effect: true
    effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
    flash: true
    optimistic: false
    qos: 0
  - platform: mqtt_json
    command_topic: "/eerste/slaapkamer/rgb/set4"
    brightness: true
    name: mqtt_json_slaapkamer4
    state_topic: "/eerste/slaapkamer/rgb/state"
    rgb: true
    effect: true
    effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
    flash: true
    optimistic: false
    qos: 0
  - platform: mqtt_json
    command_topic: "/eerste/slaapkamer/rgb/set5"
    brightness: true
    name: mqtt_json_slaapkamer5
    state_topic: "/eerste/slaapkamer/rgb/state"
    rgb: true
    effect: true
    effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
    flash: true
    optimistic: false
    qos: 0
  - platform: mqtt_json
    command_topic: "/eerste/slaapkamer/rgb/set6"
    brightness: true
    name: mqtt_json_slaapkamer6
    state_topic: "/eerste/slaapkamer/rgb/state"
    rgb: true
    effect: true
    effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
    flash: true
    optimistic: false
    qos: 0
  - platform: mqtt_json
    command_topic: "/eerste/slaapkamer/rgb/set7"
    brightness: true
    name: mqtt_json_slaapkamer7
    state_topic: "/eerste/slaapkamer/rgb/state"
    rgb: true
    effect: true
    effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
    flash: true
    optimistic: false
    qos: 0
  - platform: mqtt_json
    command_topic: "/eerste/slaapkamer/rgb/set8"
    brightness: true
    name: mqtt_json_slaapkamer8
    state_topic: "/eerste/slaapkamer/rgb/state"
    rgb: true
    effect: true
    effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
    flash: true
    optimistic: false
    qos: 0
