homeassistant:
  # Name of the location where Home Assistant is running
  name: Home Linda en Sander
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0


  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize:
    !include customize.yaml


recorder:
  db_url: postgres://@/homeassistant
  purge_days: 7

logger:
  default: info
    #critical
  # info
#  logs:
#    homeassistant.components.sensor: debug
#    homeassistant.components.script: debug
#    homeassistant.components.automation: debug
#    homeassistant.components.device_tracker: debug

# Enables the frontend
frontend:

config:

http:
  # Uncomment this to add a password (recommended!)
  #api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  #ssl_certificate: !secret ssl_ssl_certificate
  #ssl_key: !secret ssl_ssl_key
  #base_url: !secret ssl_base_url


# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


sensor: !include sensors.yaml
switch: !include switches.yaml


# Text to speech
tts:
  platform: google

#device_tracker: !include device_tracker.yaml


group: !include groups.yaml
zone: !include zones.yaml
automation: !include automations.yaml
#automation: !include_dir_list automation/

#light: !include_dir_list light/
#script: !include_dir_list script/
script: !include script/badkamer_script.yaml
#script: !include script/group_visibility.yaml
input_boolean: !include input_booleans.yaml
scene: !include_dir_list scenes



# MQTT config
mqtt:
  broker: 192.168.0.9
  port: 1883
  client_id: home-assistant
  keepalive: 60
#  username: USERNAME
#  password: PASSWORD
  protocol: 3.1
  #discovery: "discovery/#"
#  birth_message:
#    topic: 'hass/status'
#    payload: 'online'
#    qos: 1
#    retain: true
#  will_message:
#    topic: 'hass/status'
#    payload: 'offline'
#    qos: 1
#    retain: true

# Z-Wave config
zwave:
  usb_path: /dev/ttyACM0
  new_entity_ids: true



#sensor:
#  - platform: dsmr
#    port: /dev/ttyP12
#    dsmr_version: 2.2

#group:
#  meter_readings:
#    name: Meter readings
#    entities:
#      - sensor.power_consumption_low
#      - sensor.power_consumption_normal
#      - sensor.gas_consumption

#climate:
#  platform: nefit
#  name: Heating
#  serial: !secret nefit_serial
#  accesskey: !secret nefit_accesskey
#  password: ! secret nefit_password

python_script:

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
#  - name: chrome
#    platform: html5
#    gcm_api_key: !secret chrome_gcm_api_key
#    gcm_sender_id: !secret chrome_gcm_sender_id

media_player:
  - platform: cast

input_select:
  humidity:
    name: Badkamer Humidity
    options:
     - low
     - medium
     - high
    initial: low
  fanstate:
    name: Itho Fan State
    options:
     - low
     - medium
     - high
    initial: low
