homeassistant:
  # Name of the location where Home Assistant is running
  name: Home Linda en Sander
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0


  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize: !include customize.yaml
  #packages: !include_dir_named packages



recorder:
  db_url: postgres://homeassistant:ereadsta@192.168.0.9/homeassistant
  purge_interval: 2
  purge_keep_days: 7
  exclude:
    domains:
      # - automation
      - weblink
      - updater
      - device_tracker
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date
      - scene.rainbow_1
      - scene.rainbow_2
      - scene.rainbow_3
      - scene.rainbow_4
      - scene.rainbow_5
      - scene.rainbow_6
      - scene.rainbow_7
      - scene.rainbow_8
      - zone.home
  include:
    entities:
      - device_tracker.phone_linda_bt
      - device_tracker.phone_linda_wifi
      - device_tracker.phone_nexus5x
      - device_tracker.phone_phone
      - device_tracker.phone_sander
      - device_tracker.phone_sander_bt
      - device_tracker.phone_sander_wifi
      - device_tracker.nut_sander
      - device_tracker.nut_linda

logger:
  default: info
    #critical
  # info
#  logs:
#    homeassistant.components.sensor: debug
#    homeassistant.components.script: debug
#    homeassistant.components.automation: debug
#    homeassistant.components.device_tracker: debug

#splunk:
#  token: !secret splunk_token

# Enables the frontend
frontend:
  javascript_version: latest
  extra_html_url:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui.html
  extra_html_url_es5:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui-es5.html

config:

http:
  # Uncomment this to add a password (recommended!)
  #api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  #ssl_certificate: !secret ssl_ssl_certificate
  #ssl_key: !secret ssl_ssl_key
  #base_url: !secret ssl_base_url


# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml


# Text to speech
tts:
  platform: google

# google:
#   client_id: !secret google_client_id
#   client_secret: !secret google_client_secret
#   track_new_calendar: false

device_tracker: !include device_tracker.yaml

group: !include groups.yaml
zone: !include zones.yaml
automation: !include automations.yaml
#automation: !include_dir_list automation/

#light: !include_dir_list light/
#script: !include_dir_list script/
#script: !include script/badkamer_script.yaml
script: !include script/scripts.yaml
#  - !include script/woonkamer.yaml
  #- !include script/mbr.yaml
#script: !include script/group_visibility.yaml
input_boolean: !include input_booleans.yaml
scene: !include_dir_list scenes

# emulated_hue:
#   host_ip: 192.168.0.9
#   listen_port: 8300
#   # advertise_ip: 192.168.0.99
#   # advertise_port: 80
#   expose_by_default: true
#   exposed_domains:
#     - light


# android_ip_webcam:
#   - host: 192.168.0.56

# MQTT config
mqtt:
  broker: 192.168.0.9
  port: 1883
  client_id: home-assistant
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant
#  username: USERNAME
#  password: PASSWORD
  protocol: 3.1
  #discovery: "discovery/#"
#  birth_message:
#    topic: 'hass/status'
#    payload: 'online'
#    qos: 1
#    retain: true
#  will_message:
#    topic: 'hass/status'
#    payload: 'offline'
#    qos: 1
#    retain: true

# Z-Wave config
zwave:
  usb_path: /dev/ttyACM0
  autoheal: false
  device_config:
    cover.level:
      invert_openclose_buttons: true

# IFTTT
ifttt:
  key: !secret ifttt_key

#sensor:
#  - platform: dsmr
#    port: /dev/ttyP12
#    dsmr_version: 2.2

#group:
#  meter_readings:
#    name: Meter readings
#    entities:
#      - sensor.power_consumption_low
#      - sensor.power_consumption_normal
#      - sensor.gas_consumption

# climate:
#   platform: nefit
#   name: Heating
#   serial: !secret nefit_serial
#   accesskey: !secret nefit_accesskey
#   password: ! secret nefit_password

python_script:

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id1
#  - name: chrome
#    platform: html5
#    gcm_api_key: !secret chrome_gcm_api_key
#    gcm_sender_id: !secret chrome_gcm_sender_id

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    allowed_chat_ids:
      - !secret telegram_chat_id1


media_player:
  - platform: cast

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - 'co_status'
      - 'smoke_status'
      - 'battery_health'
  binary_sensors:
    monitored_conditions:
      - 'online'

input_select: !include input_select.yaml
input_number: !include input_number.yaml
light: !include light.yaml



rest_command:
  play_pause:
    url: 'http://192.168.0.9:8181/zone/Woonkamer/play_pause'
  vol_up:
    url: 'http://192.168.0.9:8181/zone/Woonkamer/volume/+5'
  vol_down:
    url: 'http://192.168.0.9:8181/zone/Woonkamer/volume/-5'
  # dide_temperature_dag:
  #   url: 'http://192.168.0.9:8388/fhem?cmd=set+ThermDide+desiredTemperature+17'
  # dide_temperature_nacht:
  #   url: 'http://192.168.0.9:8388/fhem?cmd=set+ThermDide+desiredTemperature+13'

input_text:
  valvemoving:
    name: "Action:"
    initial: Valve is moving


panel_iframe:
  avalex:
    title: 'Avalex'
    url: 'https://calendar.google.com/calendar/embed?src=4uss0i67es2enb599kpt4692mtradusn%40import.calendar.google.com'
    icon: mdi:delete

shopping_list:
