- platform: mqtt_json
  command_topic: "/eerste/slaapkamer/rgb/set"
  brightness: true
  name: mqtt_json_slaapkamer
  state_topic: "/eerste/slaapkamer/rgb/state"
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash, firegrad, rainbowcycle]
  flash: true
  optimistic: false
  qos: 0
- platform: mqtt_json
  command_topic: "/eerste/slaapkamer/rgb/set1"
  brightness: true
  name: mqtt_json_slaapkamer1
  state_topic: "/eerste/slaapkamer/rgb/state"
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
  flash: true
  optimistic: false
  qos: 0
- platform: mqtt_json
  command_topic: "/eerste/slaapkamer/rgb/set2"
  brightness: true
  name: mqtt_json_slaapkamer2
  state_topic: "/eerste/slaapkamer/rgb/state"
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
  flash: true
  optimistic: false
  qos: 0
- platform: mqtt_json
  command_topic: "/eerste/slaapkamer/rgb/set3"
  brightness: true
  name: mqtt_json_slaapkamer3
  state_topic: "/eerste/slaapkamer/rgb/state"
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
  flash: true
  optimistic: false
  qos: 0
- platform: mqtt_json
  command_topic: "/eerste/slaapkamer/rgb/set4"
  brightness: true
  name: mqtt_json_slaapkamer4
  state_topic: "/eerste/slaapkamer/rgb/state"
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
  flash: true
  optimistic: false
  qos: 0
- platform: mqtt_json
  command_topic: "/eerste/slaapkamer/rgb/set5"
  brightness: true
  name: mqtt_json_slaapkamer5
  state_topic: "/eerste/slaapkamer/rgb/state"
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
  flash: true
  optimistic: false
  qos: 0
- platform: mqtt_json
  command_topic: "/eerste/slaapkamer/rgb/set6"
  brightness: true
  name: mqtt_json_slaapkamer6
  state_topic: "/eerste/slaapkamer/rgb/state"
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
  flash: true
  optimistic: false
  qos: 0
- platform: mqtt_json
  command_topic: "/eerste/slaapkamer/rgb/set7"
  brightness: true
  name: mqtt_json_slaapkamer7
  state_topic: "/eerste/slaapkamer/rgb/state"
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
  flash: true
  optimistic: false
  qos: 0
- platform: mqtt_json
  command_topic: "/eerste/slaapkamer/rgb/set8"
  brightness: true
  name: mqtt_json_slaapkamer8
  state_topic: "/eerste/slaapkamer/rgb/state"
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
  flash: true
  optimistic: false
  qos: 0
# - platform: group
#   name: Woonkamer verlichting (groep)
#   entities:
#     - light.bankje
#     - light.woonkamer_eettafel
#     - light.woonkamer_plafond_achter
#     - light.wk_achter_plafond_level
