alias: Badkamer nacht modus PIR aan
trigger:
  platform: state
  entity_id: sensor.zolder_multisensor_burglar
#light.badkamer_plafond_level_13_0
  to: "8"
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ states.sun.sun.attributes.elevation < 0 }}'
    #  condition: time
    #  after: '21:00:00'
    #  before: '5:00:00'
    - condition: numeric_state
      entity_id: light.badkamer_plafond_level_13_0
      value_template: '{% if states.light.badkamer_plafond_level.state == "on"  %}{{ states.light.badkamer_plafond_level.attributes.brightness }}{% else %}0{% endif %}'
      below: 10
action:
  - service: script.badkamer_lights
    #light.badkamer_plafond_level_13_0
    #  state: on
    data:
      brightness: 50
      entity_id: light.badkamer_plafond_level
