alias: Badkamer dag modus
trigger:
  platform: state
  entity_id: light.badkamer_plafond_level
  #light.badkamer_plafond_level_13_0
  from: "off"
  to: "on"
condition:
  condition: and
  conditions:
    - condition: time
      before: '0:00:00'
    - condition: sun
      after: sunrise
action:
  service: script.badkamer_lights
  #light.badkamer_plafond_level_13_0
  #  state: on
  data:
    brightness: 255
    entity_id: light.badkamer_plafond_level
