alias: Badkamer nacht modus PIR uit
trigger:
  platform: state
  entity_id: sensor.zolder_multisensor_burglar
#light.badkamer_plafond_level_13_0
  # script staat nu uit, verander 1000 in 0 om aan te zetten
  to: "1000"
  for:
    minutes: 5
condition:
  condition: template
  value_template: '{{ states.sun.sun.attributes.elevation < 0 }}'
  #condition: time
  #after: '21:00:00'
  #before: '5:00:00'
action:
  - service: script.badkamer_lights_off
    #light.badkamer_plafond_level_13_0
    #  state: on
    data:
      brightness: 0
      entity_id: light.badkamer_plafond_level
