alias: Badkamer ochtend modus
trigger:
  platform: state
  entity_id: light.badkamer_plafond_level
  #light.badkamer_plafond_level_13_0
  from: "off"
  to: "on"
condition:
  condition: and
  conditions:
    - condition: time
      after: '5:00:00'
    - condition: sun
      before: sunrise
action:
  - service: light.turn_on
    data:
      brightness: 50
      entity_id: light.badkamer_plafond_level
  - delay: 0:00:20
  - service: light.turn_on
    data:
      brightness: 255
      transition: 30
      entity_id: light.badkamer_plafond_level
