alias: "Fan Speed low"
trigger:
  - platform: numeric_state
    entity_id: sensor.humdelta
    below: 2
  - platform: state
    entity_id: sensor.wk_boilerstatus
    to: 'Noo'
  # platform: state
  # entity_id: sensor.bkfanhumidity, sensor.bkfanhotwater
  # to: "low"
action:
  - delay: '00:15:00'
  - service: mqtt.publish
    data:
      topic: "/hass/itho"
      payload: "low"
