alias: "Fan Speed low 2 medium"
trigger:
  - platform: numeric_state
    entity_id: sensor.humdelta
    above: 2
    below: 4
  # - platform: state
  #   entity_id: sensor.bkfanhumidity, sensor.bkfanhotwater
  #   from: "low"
  #   to: "medium"
condition:
  condition: state
  entity_id: sensor.itho_ventilatie
  state: low
action:
  service: mqtt.publish
  data:
    topic: "/hass/itho"
    payload: "medium"
