alias: Turn on Schemerlamp when sun sets
trigger:
  platform: sun
  event: sunset
  #platform: time
  #hours: 21
  #minutes: 37
condition:
  condition: state
  entity_id: group.all_devices
  state: 'home'
action:
  service: switch.turn_on
  entity_id: switch.__switch_8_0
