# Washer Notification Sequence Start
alias: 'Washer Start'
trigger:
  platform: state
  entity_id: sensor.washer_pwrup
  from: 'False'
  to: 'True'
  for:
    minutes: 3
action:
  service: input_boolean.turn_on
  entity_id: input_boolean.washer_switch
