- platform: workday
  country: NL
  workdays: [ mon, tue, wed, thu, fri ]


# NEFIT EMS script
- platform: mqtt
  name: tap_water
  state_topic: 'ems-esp/tapwater_active'
  payload_on: "1"
  payload_off: "0"

- platform: mqtt
  name: heating
  state_topic: 'ems-esp/heating_active'
  payload_on: "1"
  payload_off: "0"
# END NEFIT EMS script

- platform: template
  sensors:
    washer_pwrup:
      friendly_name: "Wasmachine status"
      value_template: "{{ states('sensor.power_meter_wasmachine') | int > 7 }}"
    dryer_pwrup:
      value_template: "{{ states('sensor.power_meter_droger') | int > 20 }}"
      friendly_name: "Droger status"
