- platform: workday
  country: NL
  workdays: [ mon, tue, wed, thu, fri ]


# NEFIT EMS script
- platform: mqtt
  name: tap_water
  state_topic: 'ems-esp/tapwater_active'
  payload_on: "1"
  payload_off: "0"

- platform: mqtt
  name: heating
  state_topic: 'ems-esp/heating_active'
  payload_on: "1"
  payload_off: "0"
# END NEFIT EMS script


# - platform: mqtt
#   name: 'Hank Button 1'
#   state_topic: "zwavejsmqtt/33/91/0/scene/001"
#   payload_on: 1
#   payload_off: 0
#   value_template: "{% if value_json.value == 0 %} 1 {% else %} 0 {% endif %}"
# - platform: mqtt
#   name: 'Hank Button 2'
#   state_topic: "zwavejsmqtt/33/91/0/scene/002"
#   payload_on: 1
#   payload_off: 0
#   value_template: "{% if value_json.value == 0 %} 1 {% else %} 0 {% endif %}"
# - platform: mqtt
#   name: 'Hank Button 3'
#   state_topic: "zwavejsmqtt/33/91/0/scene/003"
#   payload_on: 1
#   payload_off: 0
#   value_template: "{% if value_json.value == 0 %} 1 {% else %} 0 {% endif %}"
# - platform: mqtt
#   name: 'Hank Button 4'
#   state_topic: "zwavejsmqtt/33/91/0/scene/004"
#   payload_on: 1
#   payload_off: 0
#   value_template: "{% if value_json.value == 0 %} 1 {% else %} 0 {% endif %}"
  