- platform: mqtt
  name: Kamer Dide
  current_temperature_topic: "zolder/kamerdide/ventilatie/temperatuur"
  temperature_command_topic: "zolder/kamerdide/kamer/desiredTemperature/set"
  temperature_state_topic: "zolder/kamerdide/thermostaat/desiredTemperature"
  mode_state_topic: "zolder/kamerdide/thermostaat/valveposition"
  mode_state_template: "{% if value | float == 0 %} off {% else %} on {% endif %}"
  modes:
    - "off"
    - "on"
  min_temp: 10
  max_temp: 25
  intial: 13
  retain: True
- platform: mqtt
  name: Kamer Fien
  current_temperature_topic: "zolder/kamerfien/ventilatie/temperatuur"
  temperature_command_topic: "zolder/kamerfien/kamer/desiredTemperature/set"
  temperature_state_topic: "zolder/kamerfien/thermostaat/desiredTemperature"
  mode_state_topic: "zolder/kamerfien/thermostaat/valveposition"
  mode_state_template: "{% if value | float == 0 %} off {% else %} on {% endif %}"
  modes:
    - "off"
    - "on"
  min_temp: 10
  max_temp: 25
  intial: 13
  retain: True
- platform: mqtt
  name: Woonkamer
  #current_temperature_topic: "woonkamer/woonkamer/thermostaat/gemetentemperatuur"
  current_temperature_topic: "home/boiler/thermostat_data"
  current_temperature_template: "{{ value_json.thermostat_currtemp }}"
  temperature_command_topic: "woonkamer/woonkamer/thermostaat/temperature/set"
  temperature_state_topic: "woonkamer/woonkamer/thermostaat/tempsetpoint2"
  mode_state_topic: "woonkamer/woonkamer/thermostaat/boilerstatus"
#  mode_state_template: "{% if value | float == 0 %} off {% else %} on {% endif %}"
  modes:
    - "No"
    - "HW"
    - "CH"
  min_temp: 10
  max_temp: 25
  intial: 15
  retain: True
- platform: mqtt
  name: Sous vide
  modes:
    - disconnected
    - stopped
    - running
  current_temperature_topic: anova/status
  current_temperature_template: "{{ value_json.current_temp }}"
  temperature_state_topic: anova/status
  temperature_state_template: "{{ value_json.target_temp }}"
  mode_state_topic: anova/status
  mode_state_template: "{{ value_json.state }}"
  mode_command_topic: anova/command/run
  temperature_command_topic: anova/command/temp
  min_temp: 20
  max_temp: 99
# NEFIT EMS script
# https://github.com/proddy/EMS-ESP-Boiler  
- platform: mqtt
  name: Thermostat
  modes:
    - low
    - manual
    - auto

  mode_state_topic: "home/boiler/thermostat_data"
  current_temperature_topic: "home/boiler/thermostat_data"
  temperature_state_topic: "home/boiler/thermostat_data"

  temperature_command_topic: "home/boiler/thermostat_cmd_temp"
  mode_command_topic: "home/boiler/thermostat_cmd_mode"

  mode_state_template: "{{ value_json.thermostat_mode }}"
  current_temperature_template: "{{ value_json.thermostat_currtemp }}"
  temperature_state_template: "{{ value_json.thermostat_seltemp }}"

  temp_step: 0.5
# End of NEFIT EMS script