
- platform: mqtt
  command_topic: "hass/itho/cmd"
  state_topic : "hass/itho/State"
  speed_command_topic: "hass/itho/cmd"
  speed_state_topic: "hass/itho/State"
  state_value_template: "{% if value|float==0 %}State 0{% endif %}{% if value|float >0 %}State 1{% endif %}"
  speed_value_template: "{% if value|float==0 %}State 0{% endif %}{% if value|float >0 and value|float <=4 %}State {{value}}{% endif %}{% if value|float >=11 %}State 3{% endif %}"
  payload_on: "State 1"
  payload_off: "State 0"
  payload_low_speed: "State 1"
  payload_medium_speed: "State 2"
  payload_high_speed: "State 3"
  optimistic: "true"
  name: Ventilatie
  speeds:
    - low
    - medium
    - high
- platform: template
  fans:
    itho:
      friendly_name: "Itho"
      value_template: >
        {{ "off" if states('sensor.fanspeed') == 'Low' else "on" }}
      speed_template: "{{ states('sensor.fanspeed') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.fansendhigh
      turn_off:
        service: switch.turn_on
        data:
          entity_id: switch.fansendlow
      set_speed:
        service: switch.turn_on
        data_template:
          entity_id: >
            {% set mapper = { 'Timer 1':'switch.fansendtimer1','Timer 2':'switch.fansendtimer2','Timer 3':'switch.fansendtimer3','High':'switch.fansendhigh', 'Medium':'switch.fansendmedium', 'Low':'switch.fansendlow' } %}
            {{ mapper[speed] if speed in mapper else switch.fansendlow }}
      speeds:
        - 'Low'
        - 'Medium'
        - 'High'
        - 'Timer 1'
        - 'Timer 2'
        - 'Timer 3'