- platform: mqtt
  #platform: mqtt_json
  schema: json
  command_topic: "/eerste/slaapkamer/rgb/set"
  brightness: true
  name: mqtt_json_slaapkamer
  state_topic: "/eerste/slaapkamer/rgb/state"
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, firegrad, rainbowcycle]
  #flash: true
  optimistic: false
  qos: 0

# - platform: group
#   name: Woonkamer verlichting (groep)
#   entities:
#     - light.bankje
#     - light.woonkamer_eettafel
#     - light.woonkamer_plafond_achter
#     - light.wk_achter_plafond_level
- platform: group
  name: Keuken Aanrecht (groep)
  entities:
    - light.keuken_aanrecht_rechts
    - light.keuken_aanrecht_links
# - platform: mqtt_json
#   name: "MBR Disco"
#   state_topic: "eersteverdiep/mbr/disco/light"
#   command_topic: "eersteverdiep/mbr/disco/light/set"
#   effect: true
#   effect_list:
#     - bpm
#     - candy cane  
#     - confetti  
#     - cyclon rainbow  
#     - dots  
#     - fire  
#     - glitter  
#     - juggle  
#     - lightning
#     - noise  
#     - police all  
#     - police one  
#     - rainbow  
#     - rainbow with glitter  
#     - ripple  
#     - sinelon  
#     - solid  
#     - twinkle  
#   brightness: true
#   flash: true
#   rgb: true
#   optimistic: false
#   qos: 0


# - platform: mqtt
#   name: Convectorput
#   state_topic: convectorput/light/convectorput/state
#   command_topic: convectorput/light/convectorput/command
#   availability_topic: convectorput/status
#   schema: json
#   brightness: true
# - platform: mqtt
#   name: Keuken Aanrecht Links
#   state_topic: keuken_aanrecht_links/light/keuken_aanrecht_links/state
#   command_topic: keuken_aanrecht_links/light/keuken_aanrecht_links/command
#   availability_topic: keuken_aanrecht_links/status
#   schema: json
#   brightness: true
# - platform: mqtt
#   name: Keuken Aanrecht Rechts
#   state_topic: keuken_aanrecht_rechts/light/keuken_aanrecht_rechts/state
#   command_topic: keuken_aanrecht_rechts/light/keuken_aanrecht_rechts/command
#   availability_topic: keuken_aanrecht_rechts/status
#   schema: json
#   brightness: true