- platform: mqtt
  #platform: mqtt_json
  schema: json
  command_topic: "/eerste/slaapkamer/rgb/set"
  brightness: true
  name: mqtt_json_slaapkamer
  state_topic: "/eerste/slaapkamer/rgb/state"
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash, firegrad, rainbowcycle]
  flash: true
  optimistic: false
  qos: 0
# - platform: mqtt
#   #platform: mqtt_json
#   schema: json
#   command_topic: "/eerste/slaapkamer/rgb/set1"
#   brightness: true
#   name: mqtt_json_slaapkamer1
#   state_topic: "/eerste/slaapkamer/rgb/state"
#   rgb: true
#   effect: true
#   effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
#   flash: true
#   optimistic: false
#   qos: 0
# - platform: mqtt
#   #platform: mqtt_json
#   schema: json
#   command_topic: "/eerste/slaapkamer/rgb/set2"
#   brightness: true
#   name: mqtt_json_slaapkamer2
#   state_topic: "/eerste/slaapkamer/rgb/state"
#   rgb: true
#   effect: true
#   effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
#   flash: true
#   optimistic: false
#   qos: 0
# - platform: mqtt
#   #platform: mqtt_json
#   schema: json
#   command_topic: "/eerste/slaapkamer/rgb/set3"
#   brightness: true
#   name: mqtt_json_slaapkamer3
#   state_topic: "/eerste/slaapkamer/rgb/state"
#   rgb: true
#   effect: true
#   effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
#   flash: true
#   optimistic: false
#   qos: 0
# - platform: mqtt
#   #platform: mqtt_json
#   schema: json
#   command_topic: "/eerste/slaapkamer/rgb/set4"
#   brightness: true
#   name: mqtt_json_slaapkamer4
#   state_topic: "/eerste/slaapkamer/rgb/state"
#   rgb: true
#   effect: true
#   effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
#   flash: true
#   optimistic: false
#   qos: 0
# - platform: mqtt
#   #platform: mqtt_json
#   schema: json
#   command_topic: "/eerste/slaapkamer/rgb/set5"
#   brightness: true
#   name: mqtt_json_slaapkamer5
#   state_topic: "/eerste/slaapkamer/rgb/state"
#   rgb: true
#   effect: true
#   effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
#   flash: true
#   optimistic: false
#   qos: 0
# - platform: mqtt
#   #platform: mqtt_json
#   schema: json
#   command_topic: "/eerste/slaapkamer/rgb/set6"
#   brightness: true
#   name: mqtt_json_slaapkamer6
#   state_topic: "/eerste/slaapkamer/rgb/state"
#   rgb: true
#   effect: true
#   effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
#   flash: true
#   optimistic: false
#   qos: 0
# - platform: mqtt
#   #platform: mqtt_json
#   schema: json
#   command_topic: "/eerste/slaapkamer/rgb/set7"
#   brightness: true
#   name: mqtt_json_slaapkamer7
#   state_topic: "/eerste/slaapkamer/rgb/state"
#   rgb: true
#   effect: true
#   effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
#   flash: true
#   optimistic: false
#   qos: 0
# - platform: mqtt
#   #platform: mqtt_json
#   schema: json
#   command_topic: "/eerste/slaapkamer/rgb/set8"
#   brightness: true
#   name: mqtt_json_slaapkamer8
#   state_topic: "/eerste/slaapkamer/rgb/state"
#   rgb: true
#   effect: true
#   effect_list: [colorfade_slow, colorfade_fast, flash, firegrad]
#   flash: true
#   optimistic: false
#   qos: 0
# - platform: group
#   name: Woonkamer verlichting (groep)
#   entities:
#     - light.bankje
#     - light.woonkamer_eettafel
#     - light.woonkamer_plafond_achter
#     - light.wk_achter_plafond_level
- platform: group
  name: Keuken Aanrecht (groep)
  entities:
    - light.keuken_aanrecht_rechts_2
    - light.keuken_aanrecht_links_2
# - platform: mqtt_json
#   name: "MBR Disco"
#   state_topic: "eersteverdiep/mbr/disco/light"
#   command_topic: "eersteverdiep/mbr/disco/light/set"
#   effect: true
#   effect_list:
#     - bpm
#     - candy cane  
#     - confetti  
#     - cyclon rainbow  
#     - dots  
#     - fire  
#     - glitter  
#     - juggle  
#     - lightning
#     - noise  
#     - police all  
#     - police one  
#     - rainbow  
#     - rainbow with glitter  
#     - ripple  
#     - sinelon  
#     - solid  
#     - twinkle  
#   brightness: true
#   flash: true
#   rgb: true
#   optimistic: false
#   qos: 0